UCMMarketplace/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCMMarketplace.Models;

namespace UCMMarketplace.Controllers
{
    public class HomeController : Controller
    {
        //Get : Item
        //[HttpGet]
        //public ActionResult Index()
        //{
        //    ucmmarketplaceEntities en = new ucmmarketplaceEntities();
        //    return View(en.items.ToList());
        //}

        //Get Item Data
        [HttpGet]
        public ActionResult Index(string search)
        {
            if (search == "")
            {
                ucmmarketplaceEntities en = new ucmmarketplaceEntities();
                return View(en.items.ToList());
            }
            else
            {
                ucmmarketplaceEntities en = new ucmmarketplaceEntities();
                return View(en.items.Where(x => x.Title.Contains(search) || search == null).ToList());
            }
        }
        //About Page
        public ActionResult About()
        {
            ViewBag.Message = "Buy-Sell-Go";

            return View();
        }
        //Contact Page
        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
        // GET: Category
        [HttpGet]
        public PartialViewResult GetCategory()
        {
            ucmmarketplaceEntities en = new ucmmarketplaceEntities();
            return PartialView(en.categories.ToList());
        }
        // Get : Filter images by category
        [HttpGet]
        public PartialViewResult FilterbyCategory(int CategoryID)
        {

            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {
                List<item> itemlists = en.items.ToList();
                List<Itemviewmodel> itemlist = itemlists.Select(x => new Itemviewmodel
                {
                    ItemID = x.ItemID,
                    Title = x.Title,
                    Description = x.Description,
                    Condition = x.Condition,
                    ImagePath = x.ImagePath,
                    CategoryID =x.CategoryID,
                    CategoryName = x.category.CategoryName,
                    Status = x.Status
                }).Where(x => x.CategoryID == CategoryID)
                  .OrderByDescending(x => x.ItemID)
                  .ToList();
                if (itemlist != null || itemlist.Count == 0 )
                {
                    return PartialView(itemlist);
                }else
                {
                    return PartialView(itemlists);
                }
            }
        }

    }
}

UCMMarketplace/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCMMarketplace.Models;
using System.IO;
using System.Data.Entity;
//Controller for Item tasks such as Add,Edit,View
//Code by Alpa Bandekar 04/18/2020
namespace UCMMarketplace.Controllers
{
    public class ItemController : Controller
    {
        //Get: assign Category and Condition values list of item to the drodown
        [HttpGet]
        public ActionResult Add()
        {
            using (ucmmarketplaceEntities itemimage = new ucmmarketplaceEntities())
            {
                var categorydatalist = itemimage.categories.ToList();
                SelectList catlist = new SelectList(categorydatalist, "CategoryID", "CategoryName");
                ViewBag.categoryname = catlist;
                List<SelectListItem> Condition = new List<SelectListItem>()
                {
                    new SelectListItem() { Value = "New", Text = "New", /*Selected = true, Disabled = true*/ },
                    new SelectListItem() { Value = "BarelyUsed", Text = "BarelyUsed" },
                    new SelectListItem() { Value = "Used", Text = "Used" },
                };
                ViewBag.ItemCondition = Condition;
                return View();
            }
        }
        //Post: an item for sell
        [HttpPost]
        public ActionResult Add(item item)
        {
            int UserID;
            var username = Session["UserName"].ToString();
            string imagefilename = "";
            ucmmarketplaceEntities en = new ucmmarketplaceEntities();
            UserID = en.users.Where(x => x.UserName == username).Select(x => x.UserId).FirstOrDefault();
            foreach (var file in item.Imagefile)
            {
                string filename = Path.GetFileNameWithoutExtension(file.FileName);
                string extension = Path.GetExtension(file.FileName);
                
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                if (Directory.Exists("~/ItemImages")==false)
                {
                    Directory.CreateDirectory(Server.MapPath("~/ItemImages"));
                }
                if (imagefilename == "")
                {
                    imagefilename = "~/ItemImages/" + filename;
                }
                else
                {
                    imagefilename = imagefilename + "|" + "~/ItemImages/" + filename;
                }
                filename = Path.Combine(Server.MapPath("~/ItemImages/"), filename);
                file.SaveAs(filename);
            }
                using (ucmmarketplaceEntities itemimage = new ucmmarketplaceEntities())
                {
                    if (imagefilename != "") { item.ImagePath = imagefilename; }
                    item.Status = "Available";
                    item.Description = item.Description;
                    item.Condition = item.ItemCond;
                    item.Price = Convert.ToDouble(item.Price);
                    item.CategoryList = item.CategoryList;
                    item.CategoryID = Convert.ToInt32(item.CategoryList);
                    item.UploadUserID = Convert.ToInt32(UserID); 
                    itemimage.items.Add(item);
                    itemimage.SaveChanges();

                }
               
            
            ModelState.Clear();
            return RedirectToAction("Index", "Home");

        }
        //Get: View an item
        [HttpGet]
        public ActionResult View(int id)
        {
            item itemimage = new item();

            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {

                List<item> itemlists = en.items.ToList();
                if (Session["UserName"] != null)
                { 
                var username = Session["UserName"];
                var UserID = en.users.Where(x => x.UserName == username.ToString()).Select(x => x.UserId).FirstOrDefault();
                ViewBag.UserId = UserID;
                 }
                List<Itemviewmodel> itemlist = itemlists.Select(x => new Itemviewmodel
                {
                    ItemID = x.ItemID,
                    Title = x.Title,
                    Price = x.Price,
                    Description = x.Description,
                    Condition = x.Condition,
                    ImagePath = x.ImagePath,
                    CategoryName = x.category.CategoryName,
                    Status = x.Status,
                    UploadUserID = x.UploadUserID
                }).Where(x => x.ItemID == id).ToList();
                //To get Upload User data
                GetUserData1(id);
                return View(itemlist);
            }

        }
        [NonAction]
        public void GetUserData1(int itemid)
        {
            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {
                string EmailAdd;
                List<item> itemlists = en.items.ToList();
                List<GetUserData> itemlist = itemlists.Select(x => new GetUserData
                {
                    ItemID = x.ItemID,
                    UploadUserID = x.UploadUserID,
                    EmailId = x.user.EmailId,
                    UserId = x.user.UserId,
                    UserName = x.user.UserName,
                    ItemTitle = x.Title,
                }).Where(x => x.ItemID == itemid && x.UploadUserID == x.UserId).ToList();
                EmailAdd = itemlist.First().EmailId.ToString();
                ViewBag.EmailAdd = EmailAdd;
            }
        }

        //Edit an item Assign condition and status dropdown
        [HttpGet]
        public ActionResult Edit(int id)
        {
            item itemimage = new item();
            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())

            {
                itemimage = en.items.Where(x => x.ItemID == id).FirstOrDefault();
                var categorydatalist = en.categories.ToList();
                SelectList catlist = new SelectList(categorydatalist, "CategoryID", "CategoryName");
                ViewBag.categoryname = catlist;
            }
            
            List<SelectListItem> Condition = new List<SelectListItem>()
                {
                    new SelectListItem() { Value = "New", Text = "New", /*Selected = true, Disabled = true*/ },
                    new SelectListItem() { Value = "BarelyUsed", Text = "BarelyUsed" },
                    new SelectListItem() { Value = "Used", Text = "Used" },
                };
            ViewBag.ItemCondition = Condition;
            List<SelectListItem> ItemStatus = new List<SelectListItem>()
                {
                    new SelectListItem() { Value = "Available", Text = "Available", /*Selected = true, Disabled = true*/ },
                    new SelectListItem() { Value = "Sold", Text = "Sold" },
                    new SelectListItem() { Value = "PendingForPickup", Text = "PendingForPickup" },
                };
            ViewBag.ItemStatus = ItemStatus;

            return View(itemimage);
        }
        //Post: Edit an item
        [HttpPost]
        public ActionResult Edit(item item)
        {
            item itemimage = new item();

            //category cg = new category();
            //cg.categoryList = new SelectList(cg.GetCategoryList(), "CategoryID", "CateoryName");
            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {

                int UserID;
                var username = Session["UserName"];
                UserID = en.users.Where(x => x.UserName == username.ToString()).Select(x => x.UserId).FirstOrDefault();
                itemimage = en.items.Where(x => x.ItemID == item.ItemID && x.UploadUserID == UserID).FirstOrDefault();
                string imagefilename="";
                string filename1 = "";
                foreach (var file in item.Imagefile)
                {
                    if (file != null)
                    {
                        
                            string filename = Path.GetFileNameWithoutExtension(file.FileName);
                            string extension = Path.GetExtension(file.FileName);
                            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                            // item.ImagePath = "~/ItemImages/" + filename;
                            filename1 = Path.Combine(Server.MapPath("~/ItemImages/"), filename);
                            file.SaveAs(filename1);
                            if (imagefilename == "")
                            {
                                imagefilename = "~/ItemImages/" + filename;
                            }
                            else
                            {
                                imagefilename = imagefilename + "|" + "~/ItemImages/" + filename;
                            }
                        
                    }
                }
                if (ModelState.IsValid)
                {
                    itemimage.Title = item.Title;
                    if (imagefilename == null || imagefilename=="") { 
                        itemimage.ImagePath = itemimage.ImagePath; 
                    } else {
                        itemimage.ImagePath = imagefilename; 
                    }
                    
                    itemimage.Description = item.Description;
                    if (item.Status != "" || item.Status != null)
                    {
                        itemimage.Status = item.Status;
                    }
                    else
                    {
                        itemimage.Status = itemimage.Status;
                    }
                    
                    if (item.Condition != "" || item.Condition != null)
                        {
                            itemimage.Condition = item.Condition;
                        }
                    else

UCMMarketplace/Controllers/WishlistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCMMarketplace.Models;

namespace UCMMarketplace.Controllers
{
    public class WishlistController : Controller
    {
        // GET: SaveItemtoWishlist
        [HttpGet]
        public ActionResult SaveItemtoWishlist(int itemid)
        {
            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {
                wishlist objwishlist = new wishlist();
                if (Session["UserName"] != null || Session["UserName"].ToString() != "")
                {
                    int UserID;
                    var username = Session["UserName"].ToString();
                    UserID = en.users.Where(x => x.UserName == username).Select(x => x.UserId).FirstOrDefault();
                    objwishlist.UserID = UserID;
                    objwishlist.ItemID = itemid;
                    en.wishlists.Add(objwishlist);
                    en.SaveChanges();
                }

            }
            return View();
        }
        //Removes Item from Wishlist
        public ActionResult RemoveItemfromWishlist(int itemid)
        {
            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {
                wishlist objwishlist = new wishlist();
                if (Session["UserName"] != null || Session["UserName"].ToString() != "")
                {
                    int UserID;
                    var username = Session["UserName"].ToString();
                    UserID = en.users.Where(x => x.UserName == username).Select(x => x.UserId).FirstOrDefault();
                    wishlist listDelete = en.wishlists.Find(UserID);
                    en.wishlists.Remove(listDelete);
                    en.SaveChanges();
                    objwishlist.UserID = UserID;
                    objwishlist.ItemID = itemid;
                    en.wishlists.Add(objwishlist);
                }
              
            }

            return View();
        }

   
    }
}

UCMMarketplace/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<i><b><p>We made it very simple and easy to go.</p></b></i>
<p>UCM MarketPlace website will showcase items which students wants to sell and whoever is in need can contact seller and get the item they want to buy.</p>

UCMMarketplace/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>


<address>
    <strong>Support:</strong>   <a href="mailto:ucmmarketemailid@gmail.com">ucmmarketemailid@gmail.com</a><br />
</address>

UCMMarketplace/Views/Home/Index.cshtml
@model IEnumerable<UCMMarketplace.Models.item>

@{
    ViewBag.Title = "Index";
}
<style>
    .thumbnail img {
        height: 250px;
        width: 100%;
    }
</style>
<h3>Happy Buying and Selling</h3>
@using (Html.BeginForm("Index", "Home", FormMethod.Get))
{
    
    <div class="container-fluid">
        <div>@Html.TextBox("search")<input type="submit" value="Search" /></div>
        @Html.Partial("GetCategory", new UCMMarketplace.Models.ucmmarketplaceEntities().categories.Where(ctg => ctg.CategoryID != 0).ToList())
    </div>
        <div class="container body-content">
            <div class="row">
                @foreach (var i in @Model)
                {
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <a href="@Url.Action("View", "Item", new { id = UrlParameter.Optional })\@i.ItemID" target="_blank">
                        <div class="thumbnail">
                            @{
                                //var s = Model.Book.Author_name.ToString();
                                var s = i.ImagePath.ToString();
                                string[] imgpath = s.Split('|');
                                <img src="@Url.Content(imgpath[0])" class="img-thumbnail" />
                            }
                            @i.Title
                        </div>
                    </a>
                 


                    @*@if (Session["UserName"] != null)
        {
           <a href="#" class="addWish" data-product=@i.ItemID><span class="glyphicon glyphicon-heart-empty"></span></a>
         @*<button type="button" id="addWish" class="btn btn-default btn-xs">
            <span class="glyphicon glyphicon-heart-empty"></span>
        </button>}*@

                    @*<button type="button" id="RemovefromWishlist" class="btn btn-default btn-xs">
            <span class="glyphicon glyphicon-heart"></span>
        </button>*@


                    <p></p>
                </div>
                }
            </div>
        </div>
}
@*<script>*@
@*$("#SaveItemtoWishlist").click(function(event)
    {
        event.preventDefault();
        var url = '@Html.Raw(@Url.Action("SaveItemtoWishlist", "Wishlist", new { itemid= @ViewBag.itemid }))' ;
        $(this).find(".glyphicon").removeClass("glyphicon-heart-empty").addClass("glyphicon-heart");
        window.location.href= url;
        //$(this).toggleClass('glyphicon glyphicon-heart-empty').toggleClass('glyphicon glyphicon-heart');
    });*@
@*$('.addWish').click(function(e) {
             e.preventDefault();
            var el = $(this),
                icon = el.find('i'), //<-- new
                itemid = el.data("product");
                // some_user_id = 2; //get user id..
             $.ajax({
                 url: '@Url.Action("SaveItemtoWishlist", "Wishlist")',
                 data: { "id": itemid },
                 done: function (result) {
                     // our methods return true or false
                     if (result) {
                       alert('added to fav');
                         $(this).removeClass().addClass('glyphicon glyphicon-heart-empty'); //<-- new
                     } else {
                       alert('removed from fav');
                         $(this).removeClass().addClass('glyphicon glyphicon-heart'); //<-- new
                     }
                 }
             });
    });*@
@*</script>*@

UCMMarketplace/Views/Home/Post.cshtml
@{
    ViewBag.Title = "Post";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>