UCMMarketplace/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCMMarketplace.Models;
using System.IO;
using System.Data.Entity;
//Controller for Item tasks such as Add,Edit,View
//Code by Alpa Bandekar 04/18/2020
namespace UCMMarketplace.Controllers
{
    public class ItemController : Controller
    {
        //Get: assign Category and Condition values list of item to the drodown
        [HttpGet]
        public ActionResult Add()
        {
            using (ucmmarketplaceEntities itemimage = new ucmmarketplaceEntities())
            {
                var categorydatalist = itemimage.categories.ToList();
                SelectList catlist = new SelectList(categorydatalist, "CategoryID", "CategoryName");
                ViewBag.categoryname = catlist;
                List<SelectListItem> Condition = new List<SelectListItem>()
                {
                    new SelectListItem() { Value = "New", Text = "New", /*Selected = true, Disabled = true*/ },
                    new SelectListItem() { Value = "BarelyUsed", Text = "BarelyUsed" },
                    new SelectListItem() { Value = "Used", Text = "Used" },
                };
                ViewBag.ItemCondition = Condition;
                return View();
            }
        }
        //Post: an item for sell
        [HttpPost]
        public ActionResult Add(item item)
        {
            int UserID;
            var username = Session["UserName"].ToString();
            string imagefilename = "";
            ucmmarketplaceEntities en = new ucmmarketplaceEntities();
            UserID = en.users.Where(x => x.UserName == username).Select(x => x.UserId).FirstOrDefault();
            foreach (var file in item.Imagefile)
            {
                string filename = Path.GetFileNameWithoutExtension(file.FileName);
                string extension = Path.GetExtension(file.FileName);
                
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                if (Directory.Exists("~/ItemImages")==false)
                {
                    Directory.CreateDirectory(Server.MapPath("~/ItemImages"));
                }
                if (imagefilename == "")
                {
                    imagefilename = "~/ItemImages/" + filename;
                }
                else
                {
                    imagefilename = imagefilename + "|" + "~/ItemImages/" + filename;
                }
                filename = Path.Combine(Server.MapPath("~/ItemImages/"), filename);
                file.SaveAs(filename);
            }
                using (ucmmarketplaceEntities itemimage = new ucmmarketplaceEntities())
                {
                    if (imagefilename != "") { item.ImagePath = imagefilename; }
                    item.Status = "Available";
                    item.Description = item.Description;
                    item.Condition = item.ItemCond;
                    item.Price = Convert.ToDouble(item.Price);
                    item.CategoryList = item.CategoryList;
                    item.CategoryID = Convert.ToInt32(item.CategoryList);
                    item.UploadUserID = Convert.ToInt32(UserID); 
                    itemimage.items.Add(item);
                    itemimage.SaveChanges();

                }
               
            
            ModelState.Clear();
            return RedirectToAction("Index", "Home");

        }
        //Get: View an item
        [HttpGet]
        public ActionResult View(int id)
        {
            item itemimage = new item();

            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {

                List<item> itemlists = en.items.ToList();
                if (Session["UserName"] != null)
                { 
                var username = Session["UserName"];
                var UserID = en.users.Where(x => x.UserName == username.ToString()).Select(x => x.UserId).FirstOrDefault();
                ViewBag.UserId = UserID;
                 }
                List<Itemviewmodel> itemlist = itemlists.Select(x => new Itemviewmodel
                {
                    ItemID = x.ItemID,
                    Title = x.Title,
                    Price = x.Price,
                    Description = x.Description,
                    Condition = x.Condition,
                    ImagePath = x.ImagePath,
                    CategoryName = x.category.CategoryName,
                    Status = x.Status,
                    UploadUserID = x.UploadUserID
                }).Where(x => x.ItemID == id).ToList();
                //To get Upload User data
                GetUserData1(id);
                return View(itemlist);
            }

        }
        [NonAction]
        public void GetUserData1(int itemid)
        {
            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {
                string EmailAdd;
                List<item> itemlists = en.items.ToList();
                List<GetUserData> itemlist = itemlists.Select(x => new GetUserData
                {
                    ItemID = x.ItemID,
                    UploadUserID = x.UploadUserID,
                    EmailId = x.user.EmailId,
                    UserId = x.user.UserId,
                    UserName = x.user.UserName,
                    ItemTitle = x.Title,
                }).Where(x => x.ItemID == itemid && x.UploadUserID == x.UserId).ToList();
                EmailAdd = itemlist.First().EmailId.ToString();
                ViewBag.EmailAdd = EmailAdd;
            }
        }

        //Edit an item Assign condition and status dropdown
        [HttpGet]
        public ActionResult Edit(int id)
        {
            item itemimage = new item();
            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())

            {
                itemimage = en.items.Where(x => x.ItemID == id).FirstOrDefault();
                var categorydatalist = en.categories.ToList();
                SelectList catlist = new SelectList(categorydatalist, "CategoryID", "CategoryName");
                ViewBag.categoryname = catlist;
            }
            
            List<SelectListItem> Condition = new List<SelectListItem>()
                {
                    new SelectListItem() { Value = "New", Text = "New", /*Selected = true, Disabled = true*/ },
                    new SelectListItem() { Value = "BarelyUsed", Text = "BarelyUsed" },
                    new SelectListItem() { Value = "Used", Text = "Used" },
                };
            ViewBag.ItemCondition = Condition;
            List<SelectListItem> ItemStatus = new List<SelectListItem>()
                {
                    new SelectListItem() { Value = "Available", Text = "Available", /*Selected = true, Disabled = true*/ },
                    new SelectListItem() { Value = "Sold", Text = "Sold" },
                    new SelectListItem() { Value = "PendingForPickup", Text = "PendingForPickup" },
                };
            ViewBag.ItemStatus = ItemStatus;

            return View(itemimage);
        }
        //Post: Edit an item
        [HttpPost]
        public ActionResult Edit(item item)
        {
            item itemimage = new item();

            //category cg = new category();
            //cg.categoryList = new SelectList(cg.GetCategoryList(), "CategoryID", "CateoryName");
            using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
            {

                int UserID;
                var username = Session["UserName"];
                UserID = en.users.Where(x => x.UserName == username.ToString()).Select(x => x.UserId).FirstOrDefault();
                itemimage = en.items.Where(x => x.ItemID == item.ItemID && x.UploadUserID == UserID).FirstOrDefault();
                string imagefilename="";
                string filename1 = "";
                foreach (var file in item.Imagefile)
                {
                    if (file != null)
                    {
                        
                            string filename = Path.GetFileNameWithoutExtension(file.FileName);
                            string extension = Path.GetExtension(file.FileName);
                            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                            // item.ImagePath = "~/ItemImages/" + filename;
                            filename1 = Path.Combine(Server.MapPath("~/ItemImages/"), filename);
                            file.SaveAs(filename1);
                            if (imagefilename == "")
                            {
                                imagefilename = "~/ItemImages/" + filename;
                            }
                            else
                            {
                                imagefilename = imagefilename + "|" + "~/ItemImages/" + filename;
                            }
                        
                    }
                }
                if (ModelState.IsValid)
                {
                    itemimage.Title = item.Title;
                    if (imagefilename == null || imagefilename=="") { 
                        itemimage.ImagePath = itemimage.ImagePath; 
                    } else {
                        itemimage.ImagePath = imagefilename; 
                    }
                    
                    itemimage.Description = item.Description;
                    if (item.Status != "" || item.Status != null)
                    {
                        itemimage.Status = item.Status;
                    }
                    else
                    {
                        itemimage.Status = itemimage.Status;
                    }
                    
                    if (item.Condition != "" || item.Condition != null)
                        {
                            itemimage.Condition = item.Condition;
                        }
                    else

UCMMarketplace/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using UCMMarketplace.Models;
//Controller for Login of existing User
//Code by:Alpa Bandekar  04/13/2020
namespace UCMMarketplace.Controllers
{
    public class LoginController : Controller
    {
        //Registration Action
        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
            //return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(user user)
        {
           
            if (ModelState.IsValid)
            {
                
                var validLogin = IsValidLogin(user.UserName, user.Password);
                if (validLogin == true)
                {
                    ViewBag.Status = true;
                    Session["UserName"] = user.UserName;
                    using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
                    {
                        user email = new user();
                        string password = Crypto.Hash(user.Password);
                        email= en.users.Where(x => x.UserName == user.UserName && x.Password == password).Select(x=> x).FirstOrDefault();
                        Session["EmailId"] = email.EmailId;
                    }
                
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Status = false;
                    return View();
                }              
                //Email is already Exists
                //var isExist = IsEmailExist(user.UserName);
                //if (isExist)
                //{
                //    ModelState.AddModelError("AccountExist", "Account already exists");
                //    return View(user);
                //}
                ////password hashing
                //user.Password = Crypto.Hash(user.Password);
                ////save to databse
                //user.IsActive = false;
                //using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
                //{
                //    en.userprofiles.Add(user);
                //    en.SaveChanges();

                //}
            }
           return View();
        }
        //Registration POST action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registration([Bind(Exclude="UserId")]user user)
        {
            bool Status = false;
            string message = "";

            //Model Validation
            if (ModelState.IsValid)
            {
                //Email is already Exists
                var isExist = IsEmailExist(user.UserName,user.EmailId);
                if (isExist)
                {
                    ModelState.AddModelError("AccountExist", "Account already exist.");
                    Status = false;
                    return View(user);
                }
                //password hashing
                user.Password = Crypto.Hash(user.Password);
                //save to databse
               // user.IsActive = false;
                using (ucmmarketplaceEntities en = new ucmmarketplaceEntities())
                {
                    en.users.Add(user);
                    en.SaveChanges();
                   
                }
                //send email to user
                SendVerificationemail(user.EmailId);
                message = user.UserName + " your registration is successful. Please login to your account.";
                Status = true;
            }


            else
            {
                message = "Invalid Request";
                Status = false;
            }
            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View(user);
        }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [NonAction]
        public bool IsEmailExist(string UserName, string EmailID )
        {
            using (ucmmarketplaceEntities entity = new ucmmarketplaceEntities())
            {
                
                var record = entity.users.Where(x => x.UserName == UserName || x.EmailId == EmailID).Select(x => x).FirstOrDefault();
                
                //var v = entity.users.Where(a => a.EmailId == email.EmailId).FirstOrDefault();
                return record != null;
            }
        }
        [NonAction]
        public bool IsValidLogin(string UserName, string Password)
        {
            using (ucmmarketplaceEntities entity = new ucmmarketplaceEntities())
            {
                string UserPassowrd= Crypto.Hash(Password);
                var v = entity.users.Where(a => a.UserName == UserName && a.Password == UserPassowrd).Select(a => new { a.UserName, a.Password,a.EmailId }).FirstOrDefault();
                if (v == null) { ViewBag.message = "Invalid Login Details. If not already registered, please Register."; }
                return v != null;
            }
        }
        [NonAction]
        public void SendVerificationemail(string emailID)
        {
            try
            {
                var fromEmail = new MailAddress("ucmmarketemailid@gmail.com", "Welcome to UCM Marketplace");
                var toEmail = new MailAddress(emailID);
                var fromEmailpwd = "Ucmproject_1";
                string subject = "Your UCM Marketplace account is created.";
                string body = "<br/><br/>Lets start selling and buying." +
                                "<br/><br/>";
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false, //to remove credentials error
                    Credentials = new NetworkCredential(fromEmail.Address, fromEmailpwd)
                };
                using (var message = new MailMessage(fromEmail, toEmail)
                {
                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true
                })
                    smtp.Send(message);
            }
            catch (Exception)
            {
                ModelState.AddModelError("message", "Could not send Welcome Email");
                ModelState.Clear();
            }
        }

    }
    
}

UCMMarketplace/Views/Shared/FilterbyCategory.cshtml
@model IEnumerable<UCMMarketplace.Models.Itemviewmodel>

@{
                /**/

                ViewBag.Title = "FilterbyCategory";
}
@*@Html.Action("Index", "Home")*@
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .thumbnail img {
        height: 250px;
        width: 100%;
    }
</style>
<h3>Happy Buying and Selling</h3>
@using (Html.BeginForm("Index", "Home", FormMethod.Get))
{ 
    
    <div class="container-fluid">
        <div>@Html.TextBox("search")<input type="submit" value="Search" /></div>
        @Html.Partial("GetCategory", new UCMMarketplace.Models.ucmmarketplaceEntities().categories.Where(ctg => ctg.CategoryID != 0).ToList())
    </div>
    <div class="container body-content">
        <div class="row">
            @foreach (var i in @Model)
            {
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <a href="@Url.Action("View", "Item", new { id = UrlParameter.Optional })\@i.ItemID" target="_blank">
                        <div class="thumbnail">
                            @{
                                //var s = Model.Book.Author_name.ToString();
                                var s = i.ImagePath.ToString();
                                string[] imgpath = s.Split('|');
                                <img src="@Url.Content(imgpath[0])" class="img-thumbnail" />
                            }
                            @i.Title
                        </div>
                    </a>
                    @*<p>
                        @i.Title
                        <img src="@Url.Content("~\\wishlist image.jpg")" width="40" height="40"/>
                    </p>*@
                    <p></p>
                </div>

            }
        </div>
    </div>

}

UCMMarketplace/Views/Shared/GetCategory.cshtml
@model IEnumerable<UCMMarketplace.Models.category>

@{
    ViewBag.Title = "Index";
}
<nav class="navbar navbar-inverse">
    <div class="container-fluid" id="Display">
        @foreach (var item in Model)
        {
            <ul class="nav navbar-nav">
                <li>
                    @Ajax.ActionLink(@item.CategoryName, "FilterbyCategory", "Home", new { CategoryID = @item.CategoryID},
                new AjaxOptions() { UpdateTargetId = "Display" })
                </li>
            </ul>
         }
            
        </div>
</nav>
    @*@Html.Partial("FilterbyCategory", new UCMMarketplace.Models.ucmmarketplaceEntities().items.Where(ctg => ctg.CategoryID == @item.CategoryID).ToList())"*@

UCMMarketplace/Views/Shared/ShowMessage.cshtml
@model IEnumerable<UCMMarketplace.Models.GetUserData>
@{
    ViewBag.Title = "Index";
}

<!--Bootstrap-->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<!--Latest stable release of jQuery Core Library-->
<script src="https://code.jquery.com/jquery-1.12.2.min.js" integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<!--Bootstrap JS-->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
</script>

@*<style>
        .modal-backdrop {
            z-index: -1;
        }
    </style>
    <button class="btn btn-success" id="showmessage" data-toggle="modal" data-target="bootstrapmodel" tabindex="-1" role="dialog" aria-hidden="true">Send Message</button>
    <div class="model fade " id="bootstrapmodel">
        <div class="modal-dialog">
            <div class="modal-content">
                @foreach (var i in Model)
                {
                    <div class="modal-header">
                        <button data-dismiss="modal" class="close"><span>&times;</span></button>
                        <div class="modal-title">Send Message to @i.UserName </div>

                    </div>
                    <div class="modal-body">
                        <input type="text" id="txtMessage" />
                        Hello
                    </div>
                    <div class="modal-footer">
                        submit
                        <button class="btn btn-primary">Submit</button>
                        <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                }
            </div>
        </div>

    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#showmessage").click(function () {
                $("#bootstrapmodel").modal('show');
            });
        });
    </script>*@
@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
{
    foreach (var i in Model)
    {
        ViewBag.itemid = i.ItemID;
        ViewBag.itemid = Convert.ToInt32(ViewBag.itemid);
        ViewBag.recievername = i.UserName;
        ViewBag.EmailId = i.EmailId;
        if (Session["UserName"] != null)
        {
            ViewBag.sendername = i.SenderUserName;
        }
        else
        {
            ViewBag.sendername = "Buyer";
        }
        ViewBag.itemtitle = i.ItemTitle;

    }

    <!-- Button trigger modal -->
    @*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
        Send Message
    </button>*@

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">@ViewBag.recievername</h4>
                </div>
                <div class="modal-body">
                    @* @Html.TextBox("Mymessage")*@
                    <textarea id="Mymessage" class="form-control" style="min-width: 100%"></textarea>
                   @* @Html.TextArea("Mymessage", "Enter Message", new { @style = "color:black" })*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    @*<input type="submit"
        value="Send" />*@
                    <button type="Submit" class="btn btn-primary" id="SendMyMessage">
                        Send
                    </button>
                    @*onclick="location.href=@Url.Action("SendMessage", "Message", new { itemid = @ViewBag.itemid })"*@
                    @*<a href="#" class="btn btn-primary" id="SendMyMessage" value="Send">Send</a>*@
                    @*<a href="@Url.Action("SendMessage", "Message", new { emailid = @ViewBag.EmailId , sendername= @ViewBag.SenderUserName, recievername = @ViewBag.Username,itemid = ViewBag.ItemID })"
        class="btn btn-primary">Send</a>*@
                    @*<a class="SendMyMessage" href="">Send</a>*@
                </div>
            </div>
        </div>
    </div>
    @ViewBag.Mymessage
    
}
<script>
    $("#SendMyMessage").click(function(event)
    {
        event.preventDefault();
        
        var url = '@Html.Raw(@Url.Action("SendMessage", "Message", new { emailid = @ViewBag.EmailId, sendername = @ViewBag.sendername, strmessage = "strMessage", recievername = @ViewBag.recievername , itemtitle= @ViewBag.itemtitle, itemid= @ViewBag.itemid }))' ;  //, itemid = @Convert.ToInt32(ViewBag.ItemID) }
        var msg = $('#Mymessage').val();
        if (msg != "") {
            url = url.replace('strMessage', msg);
            window.location.href = url;
        }
        
    });
    </script>
@*<script type="text/javascript">
    $(document).ready(function (event) {
            event.preventDefault();
        $(".SendMyMessage").click(function (event) {
                event.preventDefault();
                var strMessage = document.getElementById("Mymessege").innerHTML;
                var url = '@Url.Action("SendMessage", "Message", new { emailid = @ViewBag.EmailId,strMessage= "strmessage"  ,sendername = @ViewBag.SenderUserName, recievername = @ViewBag.Username, itemid = ViewBag.ItemID })' ;
                url = url.replace("strmessage", $("#Mymessege").val());
                window.location.href = url;
            });
        });*@
@*</script>*@
@*onclick="@Html.Action("SendMessage", "Message", new ViewDataDictionary { { "emailid", @ViewBag.EmailId }, { "SendUserName", @ViewBag.SenderUserName }, { "ReceiverName", @ViewBag.UserName } })"*@

UCMMarketplace/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - UCM Marketplace</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Styles.Render("~/Content/css/bootstrap-min.css")
        <!--Bootstrap JS-->
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
        </script>
        <!--Bootstrap-->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <!--Latest stable release of jQuery Core Library-->
        <script src="https://code.jquery.com/jquery-1.12.2.min.js" integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk=" crossorigin="anonymous"></script>


    </head>

    <body>
        <div class="navbar navbar-expand-sm bg-dark navbar-dark navbar-fixed-top">
            <!--navbar-inverse navbar-fixed-top">-->
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("UCM MarketPlace", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    @if (Session["UserName"] == null)
                    {
                    <ul class="nav navbar-nav mr-auto">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Post", "Login", "Login")</li>
                        <li>@Html.ActionLink("Register", "Registration", "Login")</li>
                        <li>@Html.ActionLink("Login", "Login", "Login")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                     

                    }
                    else
                    {
                    <ul class="nav navbar-nav mr-auto">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Post", "Add", "Item")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Hello " + Session["Username"], "Index", "Home")</li>
                            <li>@Html.ActionLink("My Activity", "ShowActivity", "Activity")</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                        </ul>
                       
                    }
                </div>
            </div>
        </div>
       
        
        <div class="container body-content">
           
            @RenderBody()

            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - UCM Marketplace</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    </body>
    </html>
@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-sm bg-dark navbar-dark">
        navbar-inverse navbar-fixed-top"
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div>

            </div>
            <div class="navbar-collapse collapse" id=".navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>*@